import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const inter = localFont({
  src: "../fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  weight: "300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <header>
          <div className="site-logo">Universo em Foco</div>
          <p>
            Explore o incrível mundo da astronomia e descubra segredos do cosmos
            através de artigos, imagens e muito mais!
          </p>
        </header>
        {children}
      </body>
    </html>
  );
}
